using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Linq;
using System.Web.UI.WebControls;

public partial class SRV_Storage_Reports_NewBillingReport_Rpt_Payment_Status_OF_Financial_Year_hired_Type_MPSCSC_New : System.Web.UI.Page
{
    SqlConnection con = new System.Data.SqlClient.SqlConnection(ConfigurationManager.ConnectionStrings["FCIConnectionString"].ConnectionString.ToString());
    public string qry = "";
    SqlCommand cmd = null;
    string depotid = "";
    SqlTransaction sqltran;
    string depottype = "";
    protected void Page_Load(object sender, EventArgs e)
    {
        if (!IsPostBack)
        {
            fillgrid();
            //fillgrid2();
        }
    }


    protected void fillgrid()
    {
        string constr = ConfigurationManager.ConnectionStrings["FCIConnectionString"].ConnectionString;
        using (SqlConnection con = new SqlConnection(constr))
        {
            using (SqlCommand cmd = new SqlCommand("Get_Payment_Status_of_All_Type_MPSCSC", con))
            {
                cmd.CommandType = System.Data.CommandType.StoredProcedure;
                //cmd.Parameters.AddWithValue("@GodownID", Session["GodownID"].ToString());
                using (SqlDataAdapter sda = new SqlDataAdapter())
                {
                    cmd.Connection = con;
                    sda.SelectCommand = cmd;
                    using (DataSet DS = new DataSet())
                    {
                        sda.Fill(DS);
                        if (DS.Tables[0].Rows.Count > 0)
                        {
                            GridView1.DataSource = DS.Tables[0];
                            GridView1.DataBind();
                             
                            //GridView1.FooterRow.Style.Add("text-align;font-weight: bold;text-align:right;", "right");
                            GridView1.FooterRow.Style.Add("font-weight", "bold");
                            GridView1.FooterRow.Style.Add("text-align", "right");
                            GridView1.FooterRow.Cells[1].Text = "Total";
                            //GridView1.FooterRow.Cells[2].Text = DS.Tables[0].AsEnumerable().Sum(row => row.Field<Int32>("NoOfGenerateBill")).ToString();
                            //GridView1.FooterRow.Cells[3].Text = DS.Tables[0].AsEnumerable().Sum(row => row.Field<Decimal>("BillAmt")).ToString();
                            GridView1.FooterRow.Cells[2].Text = DS.Tables[0].AsEnumerable().Sum(row => row.Field<Int32>("NoOfSUBBill")).ToString();
                            GridView1.FooterRow.Cells[3].Text = DS.Tables[0].AsEnumerable().Sum(row => row.Field<Decimal>("SUBBillAmt")).ToString();
                            //GridView1.FooterRow.Cells[6].Text = DS.Tables[0].AsEnumerable().Sum(row => row.Field<Int32>("PendingForSubmision")).ToString();
                            //GridView1.FooterRow.Cells[7].Text = DS.Tables[0].AsEnumerable().Sum(row => row.Field<Decimal>("PendingAmountForSubmision")).ToString();
                            GridView1.FooterRow.Cells[4].Text = DS.Tables[0].AsEnumerable().Sum(row => row.Field<Int32>("NoofbillPaymentReceivedFromMPSCSC")).ToString();
                            GridView1.FooterRow.Cells[5].Text = DS.Tables[0].AsEnumerable().Sum(row => row.Field<Decimal>("Gross_Amount")).ToString();
                            GridView1.FooterRow.Cells[6].Text = DS.Tables[0].AsEnumerable().Sum(row => row.Field<Decimal>("TDS_Amt")).ToString();
                            GridView1.FooterRow.Cells[7].Text = DS.Tables[0].AsEnumerable().Sum(row => row.Field<Decimal>("PaymentDecuctionbyMPSCSC")).ToString();
                            GridView1.FooterRow.Cells[8].Text = DS.Tables[0].AsEnumerable().Sum(row => row.Field<Decimal>("PaymentReceivedAfterDeduction")).ToString();
                            GridView1.FooterRow.Cells[9].Text = DS.Tables[0].AsEnumerable().Sum(row => row.Field<Decimal>("PendingatMPSCSC")).ToString();

                        }
                        else
                        {
                            GridView1.DataSource = DS.Tables[0];
                            GridView1.DataBind();
                        }
                    }
                }
            }
        }
    }



    //protected void OnDataBound(object sender, EventArgs e)
    //{
    //    GridViewRow row = new GridViewRow(0, 0, DataControlRowType.Header, DataControlRowState.Normal);
    //    TableHeaderCell cell = new TableHeaderCell();
    //    cell.Text = "";
    //    cell.ColumnSpan = 2;
    //    row.Controls.Add(cell);

    //    cell = new TableHeaderCell();
    //    cell.ColumnSpan = 6;
    //    cell.Text = "Storage Charges Bill Generated by Branch Manager";
    //    row.Controls.Add(cell);

    //    cell = new TableHeaderCell();
    //    cell.ColumnSpan = 6;
    //    cell.Text = "Storage Charges Payment Status From MPSCSC";
    //    row.Controls.Add(cell);


    //    row.BackColor = ColorTranslator.FromHtml("#3AC0F2");
    //    GridView1.HeaderRow.Parent.Controls.AddAt(0, row);
    //}

    protected void OnDataBound(object sender, EventArgs e)
    {
        // ❗ VERY IMPORTANT NULL CHECK
        if (GridView1.HeaderRow == null)
            return;

        GridViewRow row = new GridViewRow(0, 0,
            DataControlRowType.Header,
            DataControlRowState.Normal);

        TableHeaderCell cell = new TableHeaderCell();
        cell.Text = "";
        cell.ColumnSpan = 2;
        row.Controls.Add(cell);

        cell = new TableHeaderCell();
        cell.ColumnSpan = 4;
        cell.Text = "Storage Charges Bill Generated by Branch Manager";
        row.Controls.Add(cell);

        cell = new TableHeaderCell();
        cell.ColumnSpan = 4;
        cell.Text = "Storage Charges Payment Status From MPSCSC";
        row.Controls.Add(cell);

        row.BackColor = ColorTranslator.FromHtml("#3AC0F2");
        row.ForeColor = Color.White;
        row.Font.Bold = true;

        // ✔️ Safe add
        GridView1.HeaderRow.Parent.Controls.AddAt(0, row);
    }


    protected void GridView1_RowDataBound(object sender, GridViewRowEventArgs e)
    {
        if (e.Row.RowType == DataControlRowType.DataRow)
        {
            // Format numeric cells
            if (e.Row.Cells.Count > 2) // NoOfSUBBill
                //e.Row.Cells[2].Text = string.Format("{0:N0}", Convert.ToInt32(e.Row.Cells[2].Text));
                e.Row.Cells[2].Text = Convert .ToDecimal(e.Row.Cells[2].Text).ToString("N0");
            if (e.Row.Cells.Count > 3) // SUBBillAmt
                e.Row.Cells[3].Text = string.Format("{0:N2}", Convert.ToDecimal(e.Row.Cells[3].Text));

            // Continue for other cells...
        }
        else if (e.Row.RowType == DataControlRowType.Footer)
        {
            // Footer formatting if needed
            e.Row.Font.Bold = true;
        }
    }
    protected void ddlMonth_SelectedIndexChanged(object sender, EventArgs e)
    {
        fillgrid();
    }

}