<%@ Page Title="" Language="C#" MasterPageFile="~/WareHouseMaster.master" AutoEventWireup="true" CodeFile="Rpt_Get_Rent_Bill_Generation_Pendancy_SUMMARY_New.aspx.cs" Inherits="Reports_NewBillingReports_Rpt_Get_Rent_Bill_Generation_Pendancy_SUMMARY_New" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPageHead" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPageBody" Runat="Server">
    <div>
    <fieldset>
        <legend align="center">Region, District, Wise Pending Rent Bill Generation From Aug. 2020<label style="color: red">(In M.T.)</label></legend>
        <div id="divdivision" runat="server" visible="false" class="row" style="margin-top: 15px">
            <div class="table-responsive">
                <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="false" ShowFooter="true"
                    CssClass="table table-bordered table-striped table-hover GridViewScrollHeader" 
                    OnRowDataBound="GridView1_RowDataBound"
                    OnRowCreated="GridView1_RowCreated"
                    AlternatingRowStyle-CssClass="alt" PagerStyle-CssClass="pgr">
                    <Columns>
                        <asp:TemplateField HeaderText="S.No.">
                            <ItemTemplate>
                                <%# Container.DataItemIndex + 1 %>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:BoundField DataField="Regionnm" HeaderText="Region" ItemStyle-HorizontalAlign="Left" />
                        <asp:BoundField DataField="Region_ID" HeaderText="Region_ID" ItemStyle-HorizontalAlign="Left" />
                        <asp:BoundField DataField="District_Name" HeaderText="District" ItemStyle-HorizontalAlign="Left" />
                        <asp:BoundField DataField="TotalSCBillGenerated" HeaderText="Total SC Bill Generated by Branch Manager" ItemStyle-HorizontalAlign="Right" />
                        <asp:BoundField DataField="TotalRentBillGenerated" HeaderText="Total Rent Bill Generated by Godown Owner" ItemStyle-HorizontalAlign="Right" />
                        <asp:BoundField DataField="PendingRentBillForGenerate" HeaderText="Pending Bill For Generation by Godown Owner" ItemStyle-HorizontalAlign="Right" />
                        </Columns>
                    <FooterStyle BackColor="#666633" Font-Bold="True" ForeColor="Black" />
                </asp:GridView>
            </div>
        </div>
    </fieldset>
</div>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPageWidget" Runat="Server">
</asp:Content>
<asp:Content ID="Content5" ContentPlaceHolderID="ContentPageScript" runat="Server">

<script type="text/javascript">
    function InitGridDataTable(gridId) {

        var grid = $('#' + gridId);

        if (grid.length === 0 || grid.find('tr').length <= 1) {
            return;
        }

        // Destroy old instance
        if ($.fn.DataTable.isDataTable(grid)) {
            grid.DataTable().destroy();
        }

        // THEAD fix (MOST IMPORTANT)
        if (grid.find('thead').length === 0) {
            var thead = $('<thead></thead>');
            thead.append(grid.find('tr:first'));
            grid.prepend(thead);
        }

        grid.DataTable({
            paging: true,
            searching: true,
            ordering: true,
            info: true,
            pageLength: 25,
            destroy: true
        });
    }
</script>

</asp:Content>

